#!/bin/bash

src="$1"

ffmpeg -i ${src} -s 640x1136 ../ios/Chat/splash/Default-568h@2x~iphone.png -y
ffmpeg -i ${src} -s 750x1334 ../ios/Chat/splash/Default-667h.png -y
ffmpeg -i ${src} -s 1242x2208 ../ios/Chat/splash/Default-736h.png -y
ffmpeg -i ${src} -s 640x960 ../ios/Chat/splash/Default@2x~iphone.png -y
ffmpeg -i ${src} -s 320x480 ../ios/Chat/splash/Default~iphone.png -y
ffmpeg -i ${src} -s 320x568 ../ios/Chat/splash/splash.png -y
cp ../ios/Chat/splash/splash.png ../App/resource/image/splash/splash.png
cp ../ios/Chat/splash/splash.png ../App/node_modules/@remobile/react-native-splashscreen/android/src/main/res/drawable/splash.png
