module.exports = (function() {
    var error = {
        INVALID_INPUT: "INVALID_INPUT",
        USER_NAME_DUPLICATE: "USER_NAME_DUPLICATE",
        USER_ID_DUPLICATE: "USER_ID_DUPLICATE",
        USER_ID_NOT_EXIST: "USER_ID_NOT_EXIST",
        USER_NOT_NOLINE: "USER_NOT_NOLINE",
        PASSWORD_ERROR: "PASSWORD_ERROR",
        LOGIN_MORE_TIMES: "LOGIN_MORE_TIMES",
        GROUP_NOT_EXIST: "GROUP_NOT_EXIST",
        GROUP_JOIN_MORE_TIMES: "GROUP_JOIN_MORE_TIMES",
        GROUP_NAME_DUPLICATE: "GROUP_NAME_DUPLICATE",
        GROUP_NOT_CREATOR: "GROUP_NOT_CREATOR",
        UNKNOWN_ERROR: "UNKNOWN_ERROR"
    };
    return error;
})();
